name: 01 - Building Blocks
on:
  - push
  - workflow_dispatch


jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed steps
        run: |
          echo "it is failing"
          exit 1
      - name: Say Goodbye
        run: echo "Goodbye!!"



